### ISSUE TITLE
New entry for Seney National Wildlife Refuge

### ISSUE THREAD

**Issue by JoannaMcCaffrey** [iDigBio/idb-us-collections#491]
```json
{
  "institution": "Seney National Wildlife Refuge",
  "collection": "Herbarium",
  "recordsets": "b027383d-6705-4d06-8514-db6ef16efdb5",
  "institution_code": "SENEY",
  "collection_code": "",
  "collection_uuid": "",
  "collection_lsid": "",
  "collection_url": "https://www.fws.gov/refuge/Seney/​",
  "collection_catalog_url": "",
  "contact": "Dr. Greg Corace",
  "contact_role": "",
  "contact_email": "greg_corace@fws.gov",
  "taxonomic_coverage": "",
  "geographic_range": "",
  "collection_size": "",
  "mailing_address": "1674 Refuge Entrance Rd.",
  "mailing_city": "Seney",
  "mailing_state": "Michigan",
  "mailing_zip": "49883",
  "physical_address": "1674 Refuge Entrance Rd.",
  "physical_city": "Seney",
  "physical_state": "Michigan",
  "physical_zip": "49883",
  "update_url": "",
  "lat": 46.2898869,
  "lon": -85.9493547
}
```

**Comment by JoannaMcCaffrey** [comment]
I don't have the syntactic sugar the new records, but you get the idea. Contact info from Aaron Goldberg (GLI TCN)

**Comment by kevinlove** [comment]
@JoannaMcCaffrey I'm going to go ahead and create this new record, although I have a question about our process and the metadata that I hope we can work out:

Since these records *always* represent *collections*, should "collection_code" always have a value and be a required field?

If we are using these records to represent institutions, the answer to this question is clear, but I feel like we are in a grey area here. 

Thoughts?

**Comment by JoannaMcCaffrey** [comment]
@kevinlove Not all collections/datasets have a collectionCode - look at a lot of herbaria for example.
